PuntoDeVentaAlm/Controllers/LoteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PuntoDeVentaAlm.Models;
using PuntoDeVentaAlm.Utilerias;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using CrystalDecisions.ReportSource;
using System.IO;

namespace PuntoDeVentaAlm.Controllers
{
    [Authorize(Users = "eloyola@ejemplo.com")]
    public class LoteController : Controller
    {
        private ALMENDRITAEntities db = new ALMENDRITAEntities();

        // GET: Lote
        public ActionResult Index()
        {
            if(TempData["Mensaje"] != null)
            ViewBag.Salida = TempData["Mensaje"].ToString();

            var tBL_LOTE_PRODUCCION = db.TBL_LOTE_PRODUCCION.Where(x => x.ABIERTO == true).Where(x => x.CANCELADO == false);
            return View(tBL_LOTE_PRODUCCION.ToList());
        }

        // GET: Lote/Details/5
        public ActionResult DetailsLote(string id,string product)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                product = db.TBL_PRODUCTOS.Where(y => y.ID_PRODUCTO.Equals(product)).Select(y => y.DESCRIPCION).ToList()[0];
                return RedirectToAction("Details", "DetalleLote", routeValues: new { id2 = db.TBL_DETALLE_LOTE.Where(x => x.ID_LOTE.Equals(id)).Select(x => x.ID_DETALLE).ToList()[0], producto = product,idLote=id });
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }


        // GET: Lote/Create
        public ActionResult Create()
        {
            ViewBag.DESCRIPCION = new SelectList(db.TBL_PRESENTACIONES_PRODUCT, "DESCRIPCION", "DESCRIPCION");
            return View();
        }

        public ActionResult RedireccionaCreate(string id, string idLot)
        {
            try
            {
                var validaDetalle = db.TBL_DETALLE_LOTE.Where(x => x.ID_LOTE.Equals(idLot)).Select(x => x.DISPONIBLE).ToList()[0];
                var cancelado = db.TBL_LOTE_PRODUCCION.Where(x => x.ID_LOTE.Equals(idLot)).Select(x => x.CANCELADO).ToList()[0];
                if (validaDetalle == true && cancelado==false)
                    return RedirectToAction("Edit", "DetalleLote", routeValues: new { id2 = id, idL = idLot });
                else
                {
                    TempData["Mensaje"] = "<div class=\"alert alert-warning\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button><strong>No se puede editar Stock. Consulte la sección DETALLES</strong> </div>";
                    return RedirectToAction("Index");
                }
                
            }
            catch(Exception)
            {
                return HttpNotFound();
            }
        }

        // POST: Lote/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DESCRIPCION,COSTO_PRODUCCION,FECHA_PRODUC")] TBL_LOTE_PRODUCCION tBL_LOTE_PRODUCCION)
        {
            //ID_LOTE,FECHA_REGISTRO,ABIERTO,ID_USU
            Utilerias.UtileriaComun aux = new Utilerias.UtileriaComun();
            tBL_LOTE_PRODUCCION.ID_LOTE = aux.GeneraIdProduccion();
            if (tBL_LOTE_PRODUCCION.ID_LOTE.Length == 8)
            {
                tBL_LOTE_PRODUCCION.FECHA_REGISTRO = DateTime.Now;
                tBL_LOTE_PRODUCCION.ABIERTO = true;
                tBL_LOTE_PRODUCCION.ID_USER_ASP = HttpContext.User.Identity.Name;
                tBL_LOTE_PRODUCCION.CANCELADO = false;
                var idProducto = db.TBL_PRESENTACIONES_PRODUCT.Where(x => x.DESCRIPCION.Equals(tBL_LOTE_PRODUCCION.DESCRIPCION)).Select(x => x.ID_PRODUCTO).ToList();
                tBL_LOTE_PRODUCCION.ID_PRODUC = idProducto[0];

                if (tBL_LOTE_PRODUCCION.COSTO_PRODUCCION == null)
                    tBL_LOTE_PRODUCCION.COSTO_PRODUCCION = 0;

                DetalleLoteController dlote = new DetalleLoteController();
                TBL_DETALLE_LOTE modelDetalle = new TBL_DETALLE_LOTE();
                modelDetalle.ID_LOTE = tBL_LOTE_PRODUCCION.ID_LOTE;
                modelDetalle.ID_USER_ASP = HttpContext.User.Identity.Name;
                modelDetalle.CANTIDAD = 0;
                modelDetalle.DISPONIBLE = true;

                if (ModelState.IsValid)
                {
                    db.TBL_LOTE_PRODUCCION.Add(tBL_LOTE_PRODUCCION);
                    db.SaveChanges();
                    if (dlote.Create2(modelDetalle))
                    {
                        ViewBag.Confirma = "<div class=\"alert alert-success\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button><strong>"+tBL_LOTE_PRODUCCION.ID_LOTE+" generado exitosamente.</strong> </div>";
                        return RedirectToAction("Index");
                    }
                    else
                        if(DeleteConfirmed2(tBL_LOTE_PRODUCCION.ID_LOTE))
                        {
                            ViewBag.Confirma = "<div class=\"alert alert-danger\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button><strong>Error al crear nuevo LOTE, favor de intentarlo de nuevo.</strong> </div>";
                            return RedirectToAction("Index");
                        }
                }
            }
            else
            {
                ViewBag.ID_PRODUC = new SelectList(db.TBL_PRODUCTOS, "ID_PRODUCTO", "DESCRIPCION", tBL_LOTE_PRODUCCION.ID_PRODUC);
                return View(tBL_LOTE_PRODUCCION);
            }

            ViewBag.ID_PRODUC = new SelectList(db.TBL_PRODUCTOS, "ID_PRODUCTO", "DESCRIPCION", tBL_LOTE_PRODUCCION.ID_PRODUC);
            return View(tBL_LOTE_PRODUCCION);
        }

        // GET: Lote/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TBL_LOTE_PRODUCCION tBL_LOTE_PRODUCCION = db.TBL_LOTE_PRODUCCION.Find(id);
            if (tBL_LOTE_PRODUCCION == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_PRODUC = new SelectList(db.TBL_PRODUCTOS, "ID_PRODUCTO", "DESCRIPCION", tBL_LOTE_PRODUCCION.ID_PRODUC);
            return View(tBL_LOTE_PRODUCCION);
        }

        // POST: Lote/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_LOTE,COSTO_PRODUCCION,FECHA_PRODUC,FECHA_REGISTRO,ID_PRODUC,ABIERTO,ID_USU")] TBL_LOTE_PRODUCCION tBL_LOTE_PRODUCCION)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tBL_LOTE_PRODUCCION).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_PRODUC = new SelectList(db.TBL_PRODUCTOS, "ID_PRODUCTO", "DESCRIPCION", tBL_LOTE_PRODUCCION.ID_PRODUC);
            return View(tBL_LOTE_PRODUCCION);
        }

        // GET: Lote/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TBL_LOTE_PRODUCCION tBL_LOTE_PRODUCCION = db.TBL_LOTE_PRODUCCION.Find(id);
            if (tBL_LOTE_PRODUCCION == null)
            {
                return HttpNotFound();
            }
            return View(tBL_LOTE_PRODUCCION);
        }

        // POST: Lote/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            TBL_LOTE_PRODUCCION tBL_LOTE_PRODUCCION = db.TBL_LOTE_PRODUCCION.Find(id);
            db.TBL_LOTE_PRODUCCION.Remove(tBL_LOTE_PRODUCCION);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public bool DeleteConfirmed2(string id)
        {
            TBL_LOTE_PRODUCCION tBL_LOTE_PRODUCCION = db.TBL_LOTE_PRODUCCION.Find(id);
            db.TBL_LOTE_PRODUCCION.Remove(tBL_LOTE_PRODUCCION);
            db.SaveChanges();
            return true;
        }

        [HttpPost]
        public JsonResult cancelaLote (string idLot)
        {
            try
            {
                var lot = db.TBL_LOTE_PRODUCCION.Find(idLot);
                var detLot = db.TBL_DETALLE_LOTE.Where(x => x.ID_LOTE.Equals(idLot)).ToList()[0];
                UtileriaComun aux = new UtileriaComun();
                if (detLot.VEDIDOS == 0 && aux.bajaStock(lot.ID_PRODUC, detLot.CANTIDAD, 2) )
                {
                    lot.CANCELADO = true;
                    db.SaveChanges();
                    return Json(true);
                }
                else
                    return Json(false);
            }
            catch (Exception)
            {
                return Json(false);
            }
        }

        public FileResult tarjetonLote(string id,string product)
        {
            //var ruta = Server.MapPath("");
            string ruta = @"C:\Users\Sistemas\Pictures\qrLotes\" + id + ".png";
            var l = db.TBL_LOTE_PRODUCCION.Where(x=> x.ID_LOTE.Equals(id)).ToList();
            string mensaje = String.Empty;

            if( l!= null)
                mensaje = id + "," + product+","+l[0].DESCRIPCION+","+l[0].FECHA_PRODUC;

PuntoDeVentaAlm/Views/Lote/Create.cshtml
@model PuntoDeVentaAlm.Models.TBL_LOTE_PRODUCCION

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>NUEVO LOTE</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("PRODUCTO", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DESCRIPCION", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_PRODUC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("COSTO PRODUCCION", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.COSTO_PRODUCCION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.COSTO_PRODUCCION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("FECHA PRODUCCIÓN", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA_PRODUC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA_PRODUC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Lista de Lotes", "Index")
</div>

PuntoDeVentaAlm/Views/Lote/Delete.cshtml
@model PuntoDeVentaAlm.Models.TBL_LOTE_PRODUCCION

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TBL_LOTE_PRODUCCION</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.COSTO_PRODUCCION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.COSTO_PRODUCCION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FECHA_PRODUC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA_PRODUC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FECHA_REGISTRO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA_REGISTRO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ABIERTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ABIERTO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TBL_PRODUCTOS.DESCRIPCION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TBL_PRODUCTOS.DESCRIPCION)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PuntoDeVentaAlm/Views/Lote/Details.cshtml
@model PuntoDeVentaAlm.Models.TBL_LOTE_PRODUCCION

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>DETALLES</h2>

<div>
    <h4>@Html.DisplayFor(model => model.ID_LOTE) </h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayName("PRODUCTO")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TBL_PRODUCTOS.DESCRIPCION)
        </dd>

        <dt>
            @Html.DisplayName("COSTO PRODUCCIÓN")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.COSTO_PRODUCCION)
        </dd>

        <dt>
            @Html.DisplayName("FECHA PRODUCCIÓN")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA_PRODUC)
        </dd>

    </dl>
</div>
<p> |
    @Html.ActionLink("Regresar Lista de Lotes", "Index","Lote")
</p>

PuntoDeVentaAlm/Views/Lote/Edit.cshtml
@model PuntoDeVentaAlm.Models.TBL_LOTE_PRODUCCION

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TBL_LOTE_PRODUCCION</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_LOTE)

        <div class="form-group">
            @Html.LabelFor(model => model.COSTO_PRODUCCION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.COSTO_PRODUCCION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.COSTO_PRODUCCION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FECHA_PRODUC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA_PRODUC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA_PRODUC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FECHA_REGISTRO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA_REGISTRO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA_REGISTRO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_PRODUC, "ID_PRODUC", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_PRODUC", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_PRODUC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ABIERTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ABIERTO)
                    @Html.ValidationMessageFor(model => model.ABIERTO, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PuntoDeVentaAlm/Views/Lote/Index.cshtml
@model IEnumerable<PuntoDeVentaAlm.Models.TBL_LOTE_PRODUCCION>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>PRODUCCIÓN LA ALMENDRITA</h2>

<p>
    @Html.ActionLink("Nuevo Lote", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("LOTE")
        </th>
        <th>
            @Html.DisplayName("PRODUCTO")
        </th>
        <th>
            @Html.DisplayName("COSTO")
        </th>
        <th>
            @Html.DisplayName("F. PRODUCCIÓN")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ABIERTO)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.ID_LOTE, "RedireccionaCreate", new { id = item.ID_PRODUC, idLot = item.ID_LOTE })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DESCRIPCION)
        </td>
        <td>
            $@Html.DisplayFor(modelItem => item.COSTO_PRODUCCION)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FECHA_PRODUC)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ABIERTO)
        </td>
        <td>
            | @Html.ActionLink("Detalle", "DetailsLote", new { id = item.ID_LOTE, product = item.ID_PRODUC }) |
            @Html.ActionLink("Tarjetón", "tarjetonLote", new { id = item.ID_LOTE, product = item.ID_PRODUC }, new { target = "_blank" }) |
            <input type="button" value="Cancelar" name="@item.ID_LOTE" onclick="cancelaLote(this.name)" class="btn btn-default"></td>
    </tr>
}

</table>

<div id="Cancela">
</div>
@Html.Raw(ViewBag.Salida)

@section scripts
{
    <script src="~/Scripts/jquery-ui.js"></script>
    <script>
        function cancelaLote(idLote) {
                if (confirm("DESEA CANCELAR EL LOTE?")) {

                    var url = "@Url.Action("cancelaLote","Lote")";
                    var idLot=idLote
                    var data = {idLot : idLot};

                    $.post(url, data).done(function (data) {
                        $("#Cancela").html("<div class=\"alert alert-success\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button><strong>El LOTE ha sido cancelado exitosamente.</strong> </div>")
                    }).fail("<div class=\"alert alert-warning\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button><strong>No se puede cancelar un LOTE que ya tiene ventas o salida de mercancia.</strong> </div>")
                }
        }

    </script>
}