PuntoDeVentaAlm/Controllers/InventariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PuntoDeVentaAlm.Models;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using CrystalDecisions.ReportSource;
using System.IO;

namespace PuntoDeVentaAlm.Controllers
{
    [Authorize]
    public class InventariosController : Controller
    {
        private ALMENDRITAEntities db = new ALMENDRITAEntities();

        // GET: Inventarios
        public ActionResult Index()
        {
            return View(db.TBL_INVENTARIOS.ToList());
        }

        // GET: Inventarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TBL_INVENTARIOS tBL_INVENTARIOS = db.TBL_INVENTARIOS.Find(id);
            if (tBL_INVENTARIOS == null)
            {
                return HttpNotFound();
            }
            return View(tBL_INVENTARIOS);
        }

        // GET: Inventarios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Inventarios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_INVENTARIO,FECHA,OBSERVACIONES,ESTATUS,ID_ALMACEN,ID_USER_ASP")] TBL_INVENTARIOS tBL_INVENTARIOS)
        {
            if (ModelState.IsValid)
            {
                db.TBL_INVENTARIOS.Add(tBL_INVENTARIOS);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tBL_INVENTARIOS);
        }

        // GET: Inventarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TBL_INVENTARIOS tBL_INVENTARIOS = db.TBL_INVENTARIOS.Find(id);
            if (tBL_INVENTARIOS == null)
            {
                return HttpNotFound();
            }
            return View(tBL_INVENTARIOS);
        }

        // POST: Inventarios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_INVENTARIO,OBSERVACIONES")] TBL_INVENTARIOS tBL_INVENTARIOS)
        {
            var original = db.TBL_INVENTARIOS.Find(tBL_INVENTARIOS.ID_INVENTARIO);
            original.OBSERVACIONES = tBL_INVENTARIOS.OBSERVACIONES;
            if (ModelState.IsValid)
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tBL_INVENTARIOS);
        }

        // GET: Inventarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TBL_INVENTARIOS tBL_INVENTARIOS = db.TBL_INVENTARIOS.Find(id);
            if (tBL_INVENTARIOS == null)
            {
                return HttpNotFound();
            }
            return View(tBL_INVENTARIOS);
        }

        // POST: Inventarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TBL_INVENTARIOS tBL_INVENTARIOS = db.TBL_INVENTARIOS.Find(id);
            db.TBL_INVENTARIOS.Remove(tBL_INVENTARIOS);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public PartialViewResult nuevoInventario()
        {
            ViewBag.ID_ALMACEN = new SelectList(db.TBL_ALMACENES.Where(x => x.ESTATUS == true),"ID_ALMACEN","NOM_ALMACEN");
            ViewBag.Mensaje = "";
            return PartialView("_nuevoInvent");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public PartialViewResult crearInvent([Bind (Include="ID_ALMACEN")]TBL_INVENTARIOS tBL_INVENTARIOS)
        {
            try
            {
                tBL_INVENTARIOS.FECHA = DateTime.Now;
                tBL_INVENTARIOS.ESTATUS = true;
                tBL_INVENTARIOS.ID_USER_ASP = HttpContext.User.Identity.Name;
                var valida = db.TBL_INVENTARIOS.Where(x => x.ID_ALMACEN == tBL_INVENTARIOS.ID_ALMACEN && x.ESTATUS == true).ToList();

                if (ModelState.IsValid && valida.Count()==0)
                {
                    db.TBL_INVENTARIOS.Add(tBL_INVENTARIOS);
                    db.SaveChanges();
                    ViewBag.ID_ALMACEN = new SelectList(db.TBL_ALMACENES.Where(x => x.ESTATUS == true), "ID_ALMACEN", "NOM_ALMACEN");
                    ViewBag.Mensaje = "<div class=\"alert alert-success\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button><strong>Nuevo inventario generado exitosamente.</strong> </div>";
                    return PartialView("_nuevoInvent");
                }
                else
                {
                    ViewBag.ID_ALMACEN = new SelectList(db.TBL_ALMACENES.Where(x => x.ESTATUS == true), "ID_ALMACEN", "NOM_ALMACEN");
                    ViewBag.Mensaje = "<div class=\"alert alert-warning\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button><strong>No se ha cerrado otro inventario sobre este almacenn</strong> </div>";
                    return PartialView("_nuevoInvent");
                }
            }
            catch(Exception)
            {
                ViewBag.ID_ALMACEN = new SelectList(db.TBL_ALMACENES.Where(x => x.ESTATUS == true), "ID_ALMACEN", "NOM_ALMACEN");
                ViewBag.Mensaje = "<div class=\"alert alert-danger\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button><strong>Error al generar Nuevo Inventario, favor de intentar de nuevo.</strong> </div>";
                return PartialView("_nuevoInvent");
            }
        }

        public ActionResult CargaInventario()
        {
            //Creamos variable alm para almacenar el id_almacen que se le asigno al usuario. usamos USING para recuperar dicho almacen del usuario
            int idAlm;
            using (ApplicationDbContext user = new ApplicationDbContext())
            {
                idAlm = user.Users.AsNoTracking().Where( x=> x.UserName.Equals(HttpContext.User.Identity.Name)).Select(x => x.ID_ALMACEN).ToArray()[0];
            }

            var inventActivo = db.TBL_INVENTARIOS.AsNoTracking().Where(x => x.ID_ALMACEN == idAlm && x.ESTATUS == true).ToList();

            if (inventActivo.Count == 1)
            {
                TBL_INVENTARIOS tBL_INVENTARIOS = db.TBL_INVENTARIOS.Find(inventActivo[0].ID_INVENTARIO);
                return View("CargaInventario",tBL_INVENTARIOS);
                //return View("CargaInventario",db.TBL_DETALLES_INVENT.Where( x => x.ID_INVENTARIO == inventActivo[0].ID_INVENTARIO).ToList());
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public PartialViewResult _detalleInventario(int idInvent)
        {
            int idAlm = db.TBL_INVENTARIOS.AsNoTracking().Where(x => x.ID_INVENTARIO == idInvent).Select(x => x.ID_ALMACEN).ToList()[0];
            ViewBag.nomAlm = db.TBL_ALMACENES.Where(x => x.ID_ALMACEN == idAlm).Select(x => x.NOM_ALMACEN).ToList()[0];
            return PartialView("_trabajoInventario",db.TBL_DETALLES_INVENT.Where(x => x.ID_INVENTARIO == idInvent).ToList());
        }

        public JsonResult BuscarProducto(string term)
        {
            using (ALMENDRITAEntities db = new ALMENDRITAEntities())
            {
                var resultado = db.TBL_PRODUCTOS.Where(x => x.DESCRIPCION.Contains(term)).Where(x => x.ESTATUS == true).Select(x => new { label = x.DESCRIPCION, value = x.DESCRIPCION+"|"+x.ID_PRODUCTO }).ToArray();
                return Json(resultado, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult _registraProducInvent(int idInvent)
        {
            IEnumerable<int> inv = new List<int> { idInvent };
            ViewBag.ID_INVENTARIO = new SelectList(inv);
            return PartialView("_registraInventario"); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult registraProducInvent([Bind(Include = "ID_INVENTARIO,ID_PRODUC,CANTIDAD")] TBL_DETALLES_INVENT tBL_DETALLE_INVENT)
        {
            try
            {
                //VERIFICAR QUE EL PROCESO DE INVENTAREADO NO HA SIDO CERRADO
                var inventAbierto = db.TBL_INVENTARIOS.AsNoTracking().Where(x => x.ID_INVENTARIO == tBL_DETALLE_INVENT.ID_INVENTARIO && x.ESTATUS == true).Select(x => x.ID_ALMACEN).ToArray();
                if(inventAbierto.Count() == 0)
                    return Json(new { result = 4, message = "El proceso de invetario ha sido cerrado por el administrador." }, JsonRequestBehavior.AllowGet);

                //VALIDACION CAMPOS VACIOS
                if (string.IsNullOrEmpty(tBL_DETALLE_INVENT.ID_PRODUC) || tBL_DETALLE_INVENT.CANTIDAD == 0)
                    return Json(new { result = 6, message = "No se ingreso PRODUCTO o CANTIDAD." }, JsonRequestBehavior.AllowGet);

                //OBTENER EL ID DEL PRODUCTO Y VERIFICAR QUE EXISTA EN LA BASE DE DATOS
                using(PuntoDeVentaAlm.Utilerias.UtileriaComun aux = new PuntoDeVentaAlm.Utilerias.UtileriaComun())
                {

PuntoDeVentaAlm/Views/Inventarios/CargaInventario.cshtml
@model PuntoDeVentaAlm.Models.TBL_INVENTARIOS

@{
    ViewBag.Title = "CargaInventario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>INVENTARIO</h2>

@Ajax.ActionLink("DETALLE INVENTARIO", "_detalleInventario", new { idInvent = Model.ID_INVENTARIO }, new AjaxOptions
{
    HttpMethod = "POST",
    UpdateTargetId = "detalleInventario"
})

@{Html.RenderAction("_registraProducInvent", "Inventarios", new { idInvent = Model.ID_INVENTARIO });}

<div id="detalleInventario"></div>
<div id="alert_placeholder2"></div>

    @section scripts
{
        <script>

            $(document).ready(function () {
                //FUNCION DE AUTOCOMPLETE PARA PRODUCTOS
                $(function () {
                    $("#ID_PRODUC").autocomplete({
                        source: "/Inventarios/Buscarproducto"
                    });
                });
            });

            const app = new Vue({
                el: '#formulario',
                data: {
                    producto: "",
                    cantidad: ""
                },
                methods: {
                    limpia: function () {
                        this.producto = "";
                        this.cantidad = "";
                    },
                    redefine: function (datas) {
                        this.producto = datas;
                    }
                }
            });

            $("#ID_PRODUC").blur(function () {
                app.redefine($("#ID_PRODUC").val());
            });

            function eliminaProducto(idDetInvent) {
                if (confirm("DESEA ELIMINAR REGISTRO?")) {

                    var url = "@Url.Action("eliminaRegistro", "Inventarios")";
                    var idDetInv = idDetInvent
                    var data = { idDetInv: idDetInv };

                    $.post(url, data).done(function (data) {
                        resultado2(data);

                        $("#" + idDetInv + "").attr("disabled",true);
                    })
                }
            }

            function resultado2(data) {
                switch (data.result) {
                    case 0:
                        $('#alert_placeholder2').html('<div class=\"alert alert-success\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button><strong>' + data.message + '</strong> </div>')
                        break;
                    case 1:
                        $('#alert_placeholder2').html('<div class=\"alert alert-warning\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button><strong>' + data.message + '</strong> </div>')
                        break;
                    case 2:
                        $('#alert_placeholder2').html('<div class=\"alert alert-danger\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button><strong>' + data.message + '</strong> </div>')
                        break;
                    case 3:
                        $('#alert_placeholder2').html('<div class=\"alert alert-info\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button><strong>' + data.message + '</strong> </div>')
                        break;
                }
            }

            @*var appInventarios = new Vue({
                el: '#detalleInventario',
                data: {},
                methods: {
                    eliminaProducto: function (idDetalleInvent) {
                        if (confirm("DESEA ELIMINAR REGISTRO DE INVENTARIO?."))
                        {
                            var url = "@Url.Action("eliminaRegistro","Inventarios")";
                            var idDetInvent = idDetalleInvent;
                            var data = { idDetInvent: idDetInvent };

                            this.$http.post(url, data).then(function (response) {
                                resultado2(response);
                            });
                        }
                    }
                }
            })*@
        </script>
    }

PuntoDeVentaAlm/Views/Inventarios/Create.cshtml
@model PuntoDeVentaAlm.Models.TBL_INVENTARIOS

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TBL_INVENTARIOS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FECHA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OBSERVACIONES, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OBSERVACIONES, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OBSERVACIONES, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ESTATUS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ESTATUS)
                    @Html.ValidationMessageFor(model => model.ESTATUS, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_ALMACEN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_ALMACEN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_ALMACEN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_USER_ASP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_USER_ASP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_USER_ASP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PuntoDeVentaAlm/Views/Inventarios/Delete.cshtml
@model PuntoDeVentaAlm.Models.TBL_INVENTARIOS

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TBL_INVENTARIOS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FECHA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OBSERVACIONES)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OBSERVACIONES)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ESTATUS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ESTATUS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ID_ALMACEN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_ALMACEN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ID_USER_ASP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_USER_ASP)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PuntoDeVentaAlm/Views/Inventarios/Details.cshtml
@model PuntoDeVentaAlm.Models.TBL_INVENTARIOS

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>TBL_INVENTARIOS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FECHA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OBSERVACIONES)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OBSERVACIONES)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ESTATUS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ESTATUS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ID_ALMACEN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_ALMACEN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ID_USER_ASP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_USER_ASP)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_INVENTARIO }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PuntoDeVentaAlm/Views/Inventarios/Edit.cshtml
@model PuntoDeVentaAlm.Models.TBL_INVENTARIOS

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>EDITAR</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_INVENTARIO)

        <div class="form-group">
            @Html.LabelFor(model => model.OBSERVACIONES, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.TextArea(OBSERVACIONES, new { htmlAttributes = new { @class = "form-control" } })*@
                <textarea id="OBSERVACIONES" name="OBSERVACIONES" maxlength="200" class="form-control"></textarea>
                @Html.ValidationMessageFor(model => model.OBSERVACIONES, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PuntoDeVentaAlm/Views/Inventarios/Index.cshtml
@model IEnumerable<PuntoDeVentaAlm.Models.TBL_INVENTARIOS>

@{
    ViewBag.Title = "INVENTARIOS";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>INVENTARIOS</h2>

<p>
    @Ajax.ActionLink("Nuevo Inventario", "nuevoInventario", new AjaxOptions
    { 
        HttpMethod = "POST",
        UpdateTargetId = "nuevoInv"
    })
</p>

<div id="nuevoInv">
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("ALMACEN")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FECHA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ESTATUS)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OBSERVACIONES)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TBL_ALMACENES.NOM_ALMACEN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FECHA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ESTATUS)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OBSERVACIONES)
        </td>

        <td>
            @Html.ActionLink("Editar", "Edit", new { id = item.ID_INVENTARIO })|
            @Html.ActionLink("Reporte", "reporteInvent", new { id = item.ID_INVENTARIO}, new { target = "_blank" })
          | @if (item.ESTATUS == true)
            {
                <input type="button" value="Ajustar" name="@item.ID_INVENTARIO" onclick="ajuntaInvent(this.name)" class="btn btn-default">
            }
        </td>
    </tr>
}

</table>

<div id="alert_placeholder"></div>

@section scripts
{
    <script src="~/Scripts/jquery-ui.js"></script>
    <script>
        function ajuntaInvent(idInvent) {
            if (confirm("DESEA AJUSTAR INVENTARIO? /n ESTO DARÁ POR CERRADO EL PROCESO DE INVENTARIO")) {

                var url = "@Url.Action("ajustaInventario", "Inventarios")";
                var idInv = idInvent
                var data = { idInv: idInv };

                $.post(url, data).done(function (data) {
                    resultado(data);
                })
            }
        }

        function resultado(data) {
            switch (data.result) {
                case 0:
                    $('#alert_placeholder').html('<div class=\"alert alert-success\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button><strong>' + data.message + '</strong> </div>')
                    break;
                case 1:
                    $('#alert_placeholder').html('<div class=\"alert alert-warning\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button><strong>' + data.message + '</strong> </div>')
                    break;
                case 2:
                    $('#alert_placeholder').html('<div class=\"alert alert-danger\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button><strong>' + data.message + '</strong> </div>')
                    break;
                case 3:
                    $('#alert_placeholder').html('<div class=\"alert alert-info\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button><strong>' + data.message + '</strong> </div>')
                    app.limpia();
                    break;
            }
        }

    </script>
}

PuntoDeVentaAlm/Views/Inventarios/_nuevoInvent.cshtml
@model PuntoDeVentaAlm.Models.TBL_INVENTARIOS

<div class="form-horizontal">

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">NUEVO INVENTARIO</h3>
        </div>
        <div class="panel-body">

    @using (Ajax.BeginForm("crearInvent", new AjaxOptions()
    {
        HttpMethod = "POST",
        InsertionMode = System.Web.Mvc.Ajax.InsertionMode.Replace,
        UpdateTargetId = "nuevoInv",
        Confirm = "¿Desea crear nuevo inventario?"
    }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.Label("Almacen", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ID_ALMACEN", null, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="REGISTRAR" class="btn btn-default" />
                    <br />
                </div>

            }

            @Html.Raw(ViewBag.Mensaje)
        </div>
    </div>
</div>

PuntoDeVentaAlm/Views/Inventarios/_trabajoInventario.cshtml
@model IEnumerable<PuntoDeVentaAlm.Models.TBL_DETALLES_INVENT>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">INVENTARIO DE @ViewBag.nomAlm</h3>
    </div>
    <div class="panel-body">
        <table class="table" id="detalleInventario">
            <tr>
                <th>
                    @Html.DisplayName("ID PRODUCTO")
                </th>
                <th>
                    @Html.DisplayName("DESCRIPCION")
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CANTIDAD)
                </th>
                <th>
                    @Html.DisplayName("USUARIO")
                </th>
                <th></th>
            </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ID_PRODUC)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TBL_PRODUCTOS.DESCRIPCION)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CANTIDAD)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ID_USER_ASP)
                        </td>
                        <td>
                            <input type="button" value="Eliminar" id="@item.ID_DET_INV" name="@item.ID_DET_INV" onclick="eliminaProducto(this.name)" class="btn btn-default">
                        </td>
                    </tr>
                }
        </table>

    </div>
    <div id="alert_placeholder"></div>
</div>